---
s3_bucket: "your_s3_bucket_name"
s3_object: "your_s3_object_name"
src_file_path: "/path/to/source/files"
dest_file_path: "/path/to/destination"
cc_package: "your_cc_package.tar.gz"
ai_user: "abinitio_user"
ai_grp: "abinitio_group"
cc_install_path: "/abinitio/opt/WebProducts/ControlCenter"
cc_deploy_root: "/abinitio/opt/abinitio-app-hub/apps"
cc_instance: "dev_controlcenter"
cc_ver_num: "4-2-3-5"
env_src_file: "/path/to/environment/file"
reporter_config_password: "your_reporter_password"
ab_home_path: "/path/to/abinitio/home"
web_host: "arcapp1.private-enterprise-dev.arc.travel"
app_protocol: "http"
app_port: "20000"
admin_pass: "your_admin_password"
ocagent_pass: "your_ocagent_password"
pg_host: "dev-abinitio-rds-db.cdyowoe8mbah.us-east-1.rds.amazonaws.com"
pg_db: "dev_controlcenter"
pg_port: 5432
pg_user: "abinitio"
pg_pass: "your_pg_password"
jdbc_driver_path: "/abinitio/opt/WebProducts/ControlCenter/controlcenter-4-2-3-5/ref/jdbc-drivers/postgresql-42.6.2.jar"
flash_include_option: "true"  # Example value, update as required
admin_encrypted_passwd: "your_encrypted_admin_password"
ab_app_hub_path: "/abinitio/opt/abinitio-app-hub"
db_name: "dev_controlcenter"
db_port: 5432
db_type: "postgresql"
db_host: "dev-abinitio-rds-db.cdyowoe8mbah.us-east-1.rds.amazonaws.com"
db_user: "abinitio"
