#Task to install Control-Center

- name: Creating log file
  become: False
  file:
    dest: /tmp/ansible_logs/logs_install_cc.txt
    state: touch
  delegate_to: localhost

- name: Install boto3 and botocore
  pip:
    name:
      - boto3
      - botocore
  when: not (co_ops_dir_status.stat.exists and co_ops_dir_status.stat.isdir | default(false))

- name: Download the Co-ops package from S3
  aws_s3:
    bucket: "{{ s3_bucket_name | trim }}"
    object: "{{ coop_package | trim }}"
    dest: "{{ work_directory_for_installation }}/{{ coop_package }}"
    mode: get
  when: not (co_ops_dir_status.stat.exists and co_ops_dir_status.stat.isdir | default(false))

- name: Copy and extract Installer Package from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_object }}"
    dest: "{{ dest_file_path }}/{{ cc_package }}"
    mode: get
  register: s3_download

- name: Unarchive the Installer Package
  unarchive:
    src: "{{ dest_file_path }}/{{ cc_package }}"
    dest: "{{ dest_file_path }}"
    owner: "{{ ai_user }}"
    group: "{{ ai_grp }}"
    mode: 509
  when: s3_download is success
  register: unarchive

- name: Updating log file
  become: False
  lineinfile:
    dest: /tmp/ansible_logs/logs_install_cc.txt
    state: present
    line: '- CC Package copy and extract Completed\n'
  when: unarchive is success
  delegate_to: localhost

- name: Create CC Install and Deployment directories if they don't exist
  become: True
  become_user: "{{ ai_user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ai_user }}"
    group: "{{ ai_grp }}"
    mode: 493
  with_items:
    - "{{ cc_install_path }}"
    - "{{ cc_deploy_root }}"

- name: Installing CC
  become: True
  become_user: "{{ ai_user }}"
  shell: |
    source '{{ env_src_file }}'
    pkg='{{ cc_package }}'
    cd {{ dest_file_path }}/`echo $pkg | awk -F ".tar" '{print $1}'`
    ./cc-install.ksh -install-root '{{ cc_install_path }}'
  args:
    creates: "{{ cc_install_path }}/controlcenter-{{ cc_ver_num }}"
  register: installerStatus

- name: Updating log file
  become: False
  lineinfile:
    dest: /tmp/ansible_logs/logs_install_cc.txt
    state: present
    line: '- CC Installer ran successfully\n'
  when: installerStatus is success
  delegate_to: localhost

- name: Copy Control> Center setup.properties
  template:
    src: './../templates/setup.properties.j2'
    dest: '{{ cc_install_path }}/setup.properties'
    owner: '{{ ai_user }}'
    group: '{{ ai_grp }}'
    mode: 509

- name: Creating Control> Center War file
  become: True
  become_user: '{{ ai_user }}'
  shell: |
    source '{{ env_src_file }}'
    cc-admin create {{ cc_instance }}
    cc-admin configure -batch true -propFile {{ cc_install_path }}/setup.properties
  register: warFileupload

- name: Updating log file
  become: False
  lineinfile:
    dest: /tmp/ansible_logs/logs_install_cc.txt
    state: present
    line: '- War file deployed in Web application Server\n'
  when: warFileupload is success
  delegate_to: localhost

- name: Display message of Successful completion
  debug:
    msg:
      - "CC war file is created and and placed at below location"
      - "Path: {{ cc_deploy_root }}/{{ cc_instance }}"

- name: Setting the reporter Configuration
  become: True
  become_user: '{{ ai_user }}'
  shell: |
    source '{{ env_src_file }}'
    ab-reporter start -wss-username ocagent -wss-encrypted-password {{ reporter_config_password }}

- name: Add AB_OPS_CONSOLE_URL in abinitiorc
  become: True
  become_user: '{{ ai_user }}'
  blockinfile:
    path: '{{ ab_home_path }}/config/abinitiorc'
    backup: True
    insertafter: 'EOF'
    block: |
      AB_OPS_CONSOLE_URL : {{ app_protocol }}://{{ web_host }}:{{ app_port }}/{{ cc_instance }}

- name: Updating log file
  become: False
  lineinfile:
    dest: /tmp/ansible_logs/logs_install_cc.txt
    state: present
    line: '- CC Installation Completed Successfully\n'
  when: warFileupload is success
  delegate_to: localhost
