---
- name: Create tmp directory
  file:
    path: ~/.ansible/tmp
    state: directory
    mode: 02775
    owner: "{{ ai_user }}"
    group: "{{ ai_grp }}"

- name: Create log file for Co-Operating System post installation tasks
  become: no
  file:
    path: /tmp/ansible_log_for_cops_post_tasks.txt
    state: touch
  delegate_to: localhost

- name: Perform installation test for Co>Ops
  shell: |
    source /home/{{ ai_user }}/.bashrc
    installation-test > /home/{{ ai_user }}/installation_test.output
  args:
    creates: /home/{{ ai_user }}/installation_test.output
  become: yes
  become_user: "{{ ai_user }}"
  register: install_test

- name: Log installation test result
  become: no
  lineinfile:
    path: /tmp/ansible_log_for_cops_post_tasks.txt
    state: present
    line: >
      {%- if install_test is success -%}
      - installation-test for the Co-Operating System has completed successfully
      {%- else -%}
      - installation-test for the Co-Operating System has failed
      {%- endif -%}
  delegate_to: localhost

- name: Run ab-computer-info if installation test succeeds
  shell: |
    source /home/{{ ai_user }}/.bashrc
    ab-computer-info > /home/{{ ai_user }}/ab-computer-info.output
  args:
    creates: /home/{{ ai_user }}/ab-computer-info.output
  become: yes
  become_user: "{{ ai_user }}"
  when: install_test is success
  register: ab_info

- name: Log ab-computer-info result
  become: no
  lineinfile:
    path: /tmp/ansible_log_for_cops_post_tasks.txt
    state: present
    line: >
      {%- if ab_info is success -%}
      - ab-computer info test for the Co-Operating System has completed successfully
      {%- else -%}
      - ab-computer info test for the Co-Operating System has failed
      {%- endif -%}
  delegate_to: localhost

- name: Run ab-key show if installation test succeeds
  shell: |
    source /home/{{ ai_user }}/.bashrc
    ab-key show > /home/{{ ai_user }}/ab-key-show.output
  args:
    creates: /home/{{ ai_user }}/ab-key-show.output
  become: yes
  become_user: "{{ ai_user }}"
  when: install_test is success
  register: ab_key

- name: Log ab-key show result
  become: no
  lineinfile:
    path: /tmp/ansible_log_for_cops_post_tasks.txt
    state: present
    line: >
      {%- if ab_key is success -%}
      - ab-key show test for the Co-Operating System has completed successfully
      {%- else -%}
      - ab-key show test for the Co-Operating System has failed
      {%- endif -%}
  delegate_to: localhost

- name: Run m_ls connectivity check if installation test succeeds
  shell: |
    source /home/{{ ai_user }}/.bashrc
    m_ls > /home/{{ ai_user }}/m-ls.output
  args:
    creates: /home/{{ ai_user }}/m-ls.output
  become: yes
  become_user: "{{ ai_user }}"
  when: install_test is success
  register: ls_test

- name: Log m_ls connectivity check result
  become: no
  lineinfile:
    path: /tmp/ansible_log_for_cops_post_tasks.txt
    state: present
    line: >
      {%- if ls_test is success -%}
      - m_ls connectivity test for the Co-Operating System has completed successfully
      {
